application: ememro
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

  
- url: /.*
  script: emem.py

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico
